[versions]
appcompat_version = "1.6.1"
assertk_version = "0.26.1"
constraintlayout_version = "2.1.4"
core_ktx_version = "1.12.0"
documentfile_version = "1.0.1"
flow_preferences_version = "1.9.1"
hilt_navigation_compose_version = "1.1.0"
kotlinx_coroutines_core_version = "1.7.3"
lifecycle_version = "2.6.2"
kotlin_version = "1.9.21"
hilt_version = "2.48.1"
gson_version = "2.10.1"

gradle_version = "8.2.0"

ben-manes_versions = "0.47.0"
accompanist_version = "0.32.0"

google_android_play_version = "2.1.0"

activity_version = "1.8.2"
mockk_version = "1.13.8"
navigation_compose_version = "2.7.5"
opencv_android_version = "4.5.1"
recyclerview_version = "1.3.2"
tesseract4android_version = "4.5.0"

timber_version = "5.0.1"

compose_bom_version = "2023.10.01"

kotlinCompilerExtensionVersion = "1.5.7"
ksp_version = "1.9.21-1.0.16"

junit_bom_version = "5.9.3"


[libraries]
android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle_version" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin_version" }
hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt_version" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp_version" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin_version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx_coroutines_core_version" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

fredporciuncula-flow-preferences = { module = "com.fredporciuncula:flow-preferences", version.ref = "flow_preferences_version" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk_version" }
willowtreeapps-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk_version" }

#ViewModel, LiveData
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle_version" }
lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle_version" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle_version" }

# Dagger hilt
dagger-hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt_version" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt_version" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt_version" }

# Navigation
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt_navigation_compose_version" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation_compose_version" }

# Gson
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson_version" }

# Accompanist
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist_version" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist_version" }

# Google Android play app update
google-android-play-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "google_android_play_version" }

# Activity
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity_version" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity_version" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat_version" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx_version" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile_version" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview_version" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout_version" }

opencv-android = { module = "com.github.iamareebjamal:opencv-android", version.ref = "opencv_android_version" }
tesseract4android = { module = "cz.adaptech.tesseract4android:tesseract4android", version.ref = "tesseract4android_version" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit_bom_version" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber_version" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom_version" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }


[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes_versions" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }